spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: VERSION
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: I506629
    password:
    driverClassName: org.postgresql.Driver

